name: netwolf_dio
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/pongloongyeat/netwolf/netwolf_dio
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  netwolf:
    path: ../netwolf

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
