name: netwolf_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  drift: ^2.11.1
  path: ^1.8.3
  path_provider: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.11.1
  lints: ^2.0.0
  test: ^1.21.0
