name: netwolf_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/pongloongyeat/netwolf/netwolf_core

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  meta: ^1.9.1
  sqflite: ^2.3.0

dev_dependencies:
  lint: ^2.1.2
  mocktail: ^1.0.0
  sqflite_common_ffi: ^2.3.0+2
  test: ^1.21.0
