name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./netwolf
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --set-exit-if-changed .
      - name: Run linter
        run: flutter analyze
      - name: Run tests
        run: flutter test
